apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fault-vs
spec:
  hosts:
  - nginx-svc
  http:
  - fault:
      abort:
        percentage:
          value: 100
        httpStatus: 503
    route:
    - destination:
        host: nginx-svc
